"""empty message

Revision ID: 10b6f0fbdf73
Revises: cbd8e17a077
Create Date: 2014-08-09 16:43:37.189902

"""

# revision identifiers, used by Alembic.
revision = '10b6f0fbdf73'
down_revision = 'cbd8e17a077'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
