"""empty message

Revision ID: 29f75801ef0f
Revises: 10b6f0fbdf73
Create Date: 2014-08-09 23:47:12.230449

"""

# revision identifiers, used by Alembic.
revision = '29f75801ef0f'
down_revision = '10b6f0fbdf73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('lowerbound', sa.Numeric(), nullable=True),
    sa.Column('upperbound', sa.Numeric(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate')
    ### end Alembic commands ###
