"""empty message

Revision ID: 409919b78cfd
Revises: 3f6cd27ee86a
Create Date: 2014-08-09 11:11:42.638400

"""

# revision identifiers, used by Alembic.
revision = '409919b78cfd'
down_revision = '3f6cd27ee86a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('full_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'full_name')
    ### end Alembic commands ###
