"""empty message

Revision ID: a3521db721c
Revises: 29f75801ef0f
Create Date: 2014-08-10 01:01:52.094081

"""

# revision identifiers, used by Alembic.
revision = 'a3521db721c'
down_revision = '29f75801ef0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
