"""empty message

Revision ID: cbd8e17a077
Revises: 409919b78cfd
Create Date: 2014-08-09 16:39:49.976204

"""

# revision identifiers, used by Alembic.
revision = 'cbd8e17a077'
down_revision = '409919b78cfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
