"""empty message

Revision ID: ed8a9902535
Revises: f61e33b4dd
Create Date: 2014-08-17 16:16:30.298906

"""

# revision identifiers, used by Alembic.
revision = 'ed8a9902535'
down_revision = 'f61e33b4dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
