"""initial migration

Revision ID: f61e33b4dd
Revises: None
Create Date: 2014-07-12 14:09:09.418058

"""

# revision identifiers, used by Alembic.
revision = 'f61e33b4dd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=240), nullable=True),
    sa.Column('answer', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_text'), 'question', ['text'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_text'), table_name='question')
    op.drop_table('question')
    ### end Alembic commands ###
